version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/doctor
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/nativescript-envinfo
    schedule:
      interval: daily
